/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "adder.v:1.1-15.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "adder.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "adder.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "adder.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "adder.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "adder.v:5.12-5.15" *)
  output sum;
  wire sum;
  assign cout = _01_ | _00_;
  assign _02_ = b ^ a;
  assign sum = _02_ ^ cin;
  assign _03_ = b & a;
  assign _04_ = cin & b;
  assign _00_ = _04_ | _03_;
  assign _01_ = cin & a;
endmodule
